-- Create Products Table
CREATE TABLE IF NOT EXISTS products (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    price NUMERIC(10, 2) NOT NULL,
    slashed_price NUMERIC(10, 2),
    discount TEXT,
    description TEXT NOT NULL,
    color TEXT,
    colors TEXT[] DEFAULT '{}',
    images TEXT[] DEFAULT '{}',
    tags TEXT[] DEFAULT '{}',
    features TEXT[] DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Seed Products Table with LKR Mock Products
INSERT INTO products (id, name, category, price, slashed_price, discount, description, color, colors, images, tags, features)
VALUES
(
    'headphones',
    'Pro Noise-Cancelling Headphones',
    'Audio',
    90000.00,
    120000.00,
    '25% OFF',
    'Studio-grade sound, ultimate comfort & active noise cancellation.',
    'purple',
    ARRAY['Space Purple', 'Matte Black', 'Silver Gray'],
    ARRAY['/products/headphones.webp'],
    ARRAY['audio', 'headphones', 'premium', 'wireless', 'anc'],
    ARRAY['Active Noise Cancellation', 'Studio-grade sound', '40-hour Battery']
),
(
    'charger',
    'Smart Dual Wireless Charger',
    'Power',
    27000.00,
    36000.00,
    '25% OFF',
    'Fast-charging pad for your phone and watch with a sleek leather surface.',
    'amber',
    ARRAY['Carbon Black', 'Arctic White'],
    ARRAY['/products/charger.webp'],
    ARRAY['power', 'charger', 'wireless', 'magsafe', 'leather'],
    ARRAY['Fast Dual Charging', 'Leather Surface', 'MagSafe Compatible']
),
(
    'keyboard',
    'Creations Mechanical Keyboard',
    'Gear',
    48000.00,
    63000.00,
    '24% OFF',
    'Hot-swappable tactile switches, wooden base frame, retro keycaps.',
    'blue',
    ARRAY['Onyx Black', 'Chalk White', 'Neon Purple'],
    ARRAY['/products/keyboard.webp'],
    ARRAY['gear', 'keyboard', 'mechanical', 'retro', 'tactile'],
    ARRAY['Tactile Blue Switches', 'Solid Wooden Frame', 'Retro Keycaps']
),
(
    'sleeve',
    'Minimalist Tech Sleeve',
    'Travel',
    13500.00,
    18000.00,
    '25% OFF',
    'Water-resistant canvas organizer for cords, power banks, and cards.',
    'emerald',
    ARRAY['Ash Grey', 'Midnight Black'],
    ARRAY['/products/sleeve.webp'],
    ARRAY['travel', 'sleeve', 'organizer', 'waterproof'],
    ARRAY['Water-resistant Canvas', 'Multi-pocket Layout', 'YKK Zippers']
),
(
    'lightbar',
    'Ambient LED Desk Bar',
    'Lighting',
    24000.00,
    33000.00,
    '28% OFF',
    'Monitor-mounted lighting with smart hue adjustment and music sync.',
    'pink',
    ARRAY['Matte Black', 'Silver'],
    ARRAY['/products/lightbar.webp'],
    ARRAY['lighting', 'lightbar', 'desk', 'rgb', 'smart'],
    ARRAY['Anti-glare Design', 'Music Sync Feature', 'Smart Hue Control']
),
(
    'riser',
    'Carbon Fiber Laptop Lift',
    'Gear',
    19500.00,
    27000.00,
    '27% OFF',
    'Lightweight, ultra-durable carbon fiber laptop riser.',
    'slate',
    ARRAY['Silver Gray', 'Charcoal Black'],
    ARRAY['/products/riser.webp'],
    ARRAY['gear', 'riser', 'laptop', 'carbon', 'ergonomic'],
    ARRAY['Carbon Fiber Build', 'Ergonomic Layout', 'Non-slip Pads']
),
(
    'mouse',
    'Precision Workspace Mouse',
    'Gear',
    39000.00,
    54000.00,
    '28% OFF',
    'Ergonomic workspace mouse with smart scroll wheel and silent clicks.',
    'slate',
    ARRAY['Onyx Black', 'Chalk White'],
    ARRAY['/products/mouse.webp'],
    ARRAY['gear', 'mouse', 'precision', 'silent', 'wireless'],
    ARRAY['Smart Scroll Wheel', 'Precision Sensor', 'Silent Clicks']
),
(
    'speaker',
    'Hi-Fi Studio Monitor Speaker',
    'Audio',
    105000.00,
    138000.00,
    '24% OFF',
    'High-resolution desktop monitor speakers with premium carbon cone drivers.',
    'purple',
    ARRAY['Onyx Black', 'Lunar Grey'],
    ARRAY['/products/speaker.webp'],
    ARRAY['audio', 'speaker', 'studio', 'hifi', 'wooden'],
    ARRAY['Hi-Fi Audio Drivers', 'Carbon Cone Woofers', 'Wooden Cabinet']
),
(
    'webcam',
    '4K Creator Webcam',
    'Video',
    60000.00,
    81000.00,
    '26% OFF',
    'Ultra-wide 4K webcam with automatic framing and high dynamic range.',
    'blue',
    ARRAY['Onyx Black', 'Frost White', 'Space Purple'],
    ARRAY['/products/webcam.webp'],
    ARRAY['video', 'webcam', '4k', 'hdr', 'creator'],
    ARRAY['4K Ultra HD Sensor', 'Auto-framing Tech', 'HDR Support']
),
(
    'mic',
    'USB Condenser Microphone',
    'Audio',
    54000.00,
    72000.00,
    '25% OFF',
    'Cardioid condenser microphone with dynamic noise suppression filter.',
    'emerald',
    ARRAY['Onyx Black', 'Frost White', 'Space Purple'],
    ARRAY['/products/mic.webp'],
    ARRAY['audio', 'mic', 'microphone', 'usb', 'rgb'],
    ARRAY['Cardioid Pattern', 'Built-in Pop Filter', 'RGB Live Indicator']
),
(
    'stand',
    'MagSafe Desk Mount',
    'Power',
    15000.00,
    21000.00,
    '30% OFF',
    'Magnetic phone mount machined from solid aerospace-grade aluminum.',
    'amber',
    ARRAY['Silver Gray', 'Charcoal Black'],
    ARRAY['/products/stand.webp'],
    ARRAY['power', 'stand', 'magsafe', 'magnetic', 'aluminum'],
    ARRAY['Solid Aerospace Alum', 'N52 Neodymium Magnets', '360° Rotation']
),
(
    'backpack',
    'Urban Tech Backpack',
    'Travel',
    42000.00,
    57000.00,
    '26% OFF',
    'Weatherproof layout with dedicated laptop compartment and luggage pass-through.',
    'slate',
    ARRAY['Slate Grey', 'Onyx Black'],
    ARRAY['/products/backpack.webp'],
    ARRAY['travel', 'backpack', 'bag', 'weatherproof', 'anti-theft'],
    ARRAY['Weatherproof Exterior', 'Luggage Pass-through', 'Anti-theft Pocket']
)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    category = EXCLUDED.category,
    price = EXCLUDED.price,
    slashed_price = EXCLUDED.slashed_price,
    discount = EXCLUDED.discount,
    description = EXCLUDED.description,
    color = EXCLUDED.color,
    colors = EXCLUDED.colors,
    images = EXCLUDED.images,
    tags = EXCLUDED.tags,
    features = EXCLUDED.features,
    updated_at = timezone('utc'::text, now());
